// This file was autogenerated by app/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/engine/core/component.js', ['Engine.Component'], []);
goog.addDependency('../../../js/engine/core/engine.js', ['Engine'], []);
goog.addDependency('../../../js/engine/core/system.js', ['Engine.System'], []);
goog.addDependency('../../../js/game/core/moba.js', ['Moba'], ['Engine']);
goog.addDependency('../../../js/main.js', ['main'], ['Moba']);
