// This file was autogenerated by app/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/engine/core/Component.js', ['Engine.Component'], []);
goog.addDependency('../../../js/engine/core/Core.js', ['Engine.Core'], ['Engine.EntityManager', 'Engine.FrameManager', 'Engine.SystemManager', 'goog.Timer', 'goog.events', 'goog.object']);
goog.addDependency('../../../js/engine/core/EntityManager.js', ['Engine.EntityManager'], ['goog.array']);
goog.addDependency('../../../js/engine/core/Frame.js', ['Engine.Frame'], []);
goog.addDependency('../../../js/engine/core/FrameManager.js', ['Engine.FrameManager'], ['Engine.Frame']);
goog.addDependency('../../../js/engine/core/System.js', ['Engine.System'], []);
goog.addDependency('../../../js/engine/core/SystemManager.js', ['Engine.SystemManager'], ['goog.array']);
goog.addDependency('../../../js/engine/core/engine.js', ['Engine'], ['Engine.Core']);
goog.addDependency('../../../js/game/core/Moba.js', ['Moba'], ['Engine']);
goog.addDependency('../../../js/game/simulation/simulation-bootstrap.js', ['SimulationBootstrap'], ['Simulation']);
goog.addDependency('../../../js/game/simulation/simulation.js', ['Simulation'], ['Engine', 'SimulationConfig']);
goog.addDependency('../../../js/game/systems/ExampleSystem.js', ['ExampleSystem'], []);
goog.addDependency('../../../js/main.js', ['main'], ['Moba']);
goog.addDependency('../../../js/shared/simulation-config.js', ['SimulationConfig'], ['ExampleSystem']);
goog.addDependency('app/js/main.js', ['main'], ['Moba']);
